export enum Page {
  Home = 'Home',
  Team = 'Team',
  News = 'News',
  Schedule = 'Schedule',
  Gallery = 'Gallery',
  Sponsors = 'Sponsors',
  About = 'About',
  Contact = 'Contact',
  HypeGenerator = 'Hype Generator',
  Store = 'Store',
  Checkout = 'Checkout',
  OrderConfirmation = 'OrderConfirmation',
  Admin = 'Admin Dashboard',
  Login = 'Login',
  Register = 'Register',
  PlayerDashboard = 'Player Dashboard',
  NewsDetail = 'NewsDetail',
  PrivacyPolicy = 'Privacy Policy',
  TermsOfService = 'Terms of Service',
  Sitemap = 'Sitemap',
  ForgotPassword = 'ForgotPassword',
  Classement = 'Classement',
  Live = 'Live',
}